### ISSUE TITLE
복권 발행 기능과 출력 기능에 대한 브랜치를 생성했습니다.

### ISSUE THREAD

**Issue by ankyeongeun** [f-lab-edu/lottery-game#4]
@jeansuh42 
복권 발행기능에 대한 브랜치 [feature/lottery-ticket-generation]
출력 기능에 대한 브랜치 [feature/print-lottery-game-result]
생성했습니다! 해당 브랜치에서 은빈님의 기능을 완료해주사면 됩니당.
제가 맡은 기능은 커밋했습니다. 문제가 있다면 말씀해주세요~

**Comment by jeansuh42** [comment]
[PR 생성](https://github.com/f-lab-edu/lottery-game/pull/6) 후 documentation을 종료합니다.
